# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fe2b5a75dbe89208cae5307c6adcd747b46becbf087040b8a97e8422c063d762630032a6d11ad07b3b9c6063e5acf10b087e17db118aaca4e1d114f2c5cc73c

test:
  secret_key_base: 6488bb989affcf91b3f74e546594b004fc20b65108e1d7ee70c5e2463bde3fedb28f39439275869a98ce6e9f952d7ec030df496946918429558c594c29f14356

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
